[package]
name = "replicore-tasks-sqlite"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

description = "RepliCore asyncronous tasks scheduling and execution interfaces"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
#futures = "^0.3"
once_cell = "^1.0"
opentelemetry_api = "^0.20"
prometheus = "^0.13"
refinery = { version = "^0.8", features = ["rusqlite"] }
rusqlite = { version = "^0.29", features = ["bundled"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.0"
thiserror = "^1.0"
tokio = { version = "^1.0" , features = ["time"] }
tokio-rusqlite = "^0.4"

replicore-context = { path = "../../../core/context" }
replicore-tasks = { path = "../../../core/tasks" }

replisdk = { version = "^0.1", features = [
  "utils-encoding",
  "utils-metrics",
  "utils-trace",
] }

[dev-dependencies]
tokio = { version = "^1.0", features = ["macros", "rt", "time"] }

replicore-context = { path = "../../../core/context", features = ["test-fixture"] }
replicore-tasks = { path = "../../../core/tasks", features = ["test-fixture"] }
