[package]
name = "replicante_service_coordinator"
version = "0.1.1"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Replicante distributed coordinator interface"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
keywords = ["automation", "datastore", "operations"]
license = "MIT"


[dependencies]
crossbeam-channel = "^0.5.0"
failure = "^0.1.3"
failure_derive = "^0.1.3"
humthreads = "^0.2.0"
lazy_static = "^1.0.0"
opentracingrust = "^0.4.0"
prometheus = "^0.13"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0.13"
sha2 = "^0.10"
slog = "^2.1"
zookeeper = "^0.6"

replicante_models_api = { path = "../../common/models/api" }
replicante_service_healthcheck = { path = "../healthcheck" }
replicante_util_failure = { path = "../../common/util/failure" }
replicante_util_rndid = { path = "../../common/util/rndid" }
replicante_util_tracing = { path = "../../common/util/tracing" }
