global:
  scrape_interval: 15s

scrape_configs:
  - job_name: replicante-dev-core
    metrics_path: '/api/unstable/introspect/metrics'
    static_configs:
      - targets:
        - 'host.containers.internal:16016'
