[package]
name = "replicore-oaction-platform"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

description = "RepliCore orchestration actions to perform platform operations"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1.0"
time = { version = "^0.3", features = ["formatting", "parsing", "serde"] }

replisdk = { version = "^0.1", features = [
  "platform-models",
  "replicore-models",
  "utils-error_json",
] }

replicore-context = { path = "../../../core/context"}
replicore-injector = { path = "../../../core/injector"}
replicore-oaction = { path = "../../../core/oaction" }
replicore-store = { path = "../../../core/store" }
