[package]
name = "replicore_iface_orchestrator_action"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Traits and registry for orchestrator actions"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[features]
test-api = []


[dependencies]
anyhow = "^1.0.53"
lazy_static = "^1.4.0"
serde_json = "^1.0"
thiserror = "^1.0.30"

replicante_models_core = { path = "../../../models/core" }
