[package]
name = "replicore-task-discovery"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

description = "RepliCore task to discover clusters on known platforms"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
once_cell = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
slog = "^2.0"
thiserror = "^1.0"

replisdk = { version = "^0.1", features = ["replicore-models"] }

replicore-context = { path = "../../../core/context" }
replicore-errors = { path = "../../../core/errors"}
replicore-events = { path = "../../../core/events" }
replicore-injector = { path = "../../../core/injector" }
replicore-store = { path = "../../../core/store" }
replicore-tasks = { path = "../../../core/tasks" }

[dev-dependencies]
serde_json = "^1.0"
tokio = { version = "^1.0", features = ["macros"] }

replicore-clients-platform = { path = "../../../core/clients/platform" }
replicore-injector = { path = "../../../core/injector", features = ["test-fixture"] }
repliplatform-client = { path = "../../../client/platform", features = ["test-fixture"] }
