[package]
name = "replicore-task-discovery"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

description = "RepliCore task to discover clusters on known platforms"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
once_cell = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
slog = "^2.0"

replicore-context = { path = "../../../core/context"}
replicore-tasks = { path = "../../../core/tasks" }
