//! Unit test fixture to stub out leases and inspect their use.
use std::sync::Arc;
use std::sync::Mutex;
use std::time::Duration;

use anyhow::Result;

use super::ILease;
use super::State;

/// Callback to determine the [`State`] of a lease returned by `watch`.
#[async_trait::async_trait]
pub trait ICallback<S: Send>: Send {
    /// Determine the [`State`] of a lease returned by `watch`.
    async fn invoke(&self, state: &mut S, candidate: bool) -> Result<State>;
}

/// Callback to return a fixed lease state all the time.
struct FixedLeaseCallback {
    state: State,
}

#[async_trait::async_trait]
impl ICallback<()> for FixedLeaseCallback {
    async fn invoke(&self, _: &mut (), candidate: bool) -> Result<State> {
        if candidate {
            return Ok(self.state);
        }
        Ok(State::Idle)
    }
}

impl LeaseFixture<()> {
    /// Lease fixture that returns the given state whenever watched.
    pub fn fixed(state: State) -> LeaseFixture<()> {
        let callback = FixedLeaseCallback { state };
        LeaseFixture::new((), callback)
    }
}

/// Fixture to stub out leases in unit tests.
pub struct LeaseFixture<S: Send> {
    callback: Box<dyn ICallback<S>>,
    first_watch: bool,
    notifications: LeaseFixtureNotifications,
    state: S,
    watch_delay: Duration,
}

#[async_trait::async_trait]
impl<S: Send> ILease for LeaseFixture<S> {
    async fn step_down(&mut self) -> Result<()> {
        self.notifications
            .append(LeaseFixtureNotification::SteppedDown);
        Ok(())
    }

    async fn watch(&mut self, candidate: bool) -> Result<State> {
        if !self.first_watch {
            tokio::time::sleep(self.watch_delay).await;
        }
        self.first_watch = false;

        let state = self.callback.invoke(&mut self.state, candidate).await;
        let notification = match &state {
            Ok(state) => LeaseFixtureNotification::Watched(state.clone()),
            Err(error) => LeaseFixtureNotification::WatchError(error.to_string()),
        };
        self.notifications.append(notification);
        return state;
    }
}

impl<S: Send> LeaseFixture<S> {
    /// Initialise a new lease backend for unit tests.
    pub fn new<C>(state: S, callback: C) -> LeaseFixture<S>
    where
        C: ICallback<S> + 'static,
    {
        let callback = Box::new(callback);
        LeaseFixture {
            callback,
            first_watch: true,
            notifications: Default::default(),
            state,
            watch_delay: Duration::from_millis(20),
        }
    }

    /// Get a handle to access notifications generated by the fixture.
    pub fn notifications(&self) -> LeaseFixtureNotifications {
        self.notifications.clone()
    }

    /// Set the delay time every watch call after the first will wait before returning.
    ///
    /// The watch delay is needed because lease backends are managed by a background task
    /// and therefore polled even if the test is not actively interacting with them yet.
    /// This prevents one of the tokio threads from using as much CPU as it can to forever
    /// invoke the callback and make things messier.
    ///
    /// The delay is constant across all invocations of the watch callback.
    /// If a test requires changing of the delay depending on conditions it should set this delay
    /// to zero and implement its own delay in the [`ICallback`].
    pub fn set_watch_delay(mut self, delay: Duration) -> Self {
        self.watch_delay = delay;
        self
    }
}

/// Possible notifications sent by the fixture to allow state inspection and history in tests.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LeaseFixtureNotification {
    /// A step down request was handled.
    SteppedDown,

    /// The fixture callback was invoked, moving the lease to the given state.
    Watched(State),

    /// The fixture callback was invoked, resulting in an error.
    WatchError(String),
}

/// Shared access to the fixture notifications set.
#[derive(Clone, Default)]
pub struct LeaseFixtureNotifications {
    /// List of received notifications being tracked.
    entries: Arc<Mutex<Vec<LeaseFixtureNotification>>>,
}

impl LeaseFixtureNotifications {
    /// Append a notification to the notifications set.
    fn append(&self, notification: LeaseFixtureNotification) {
        let mut entries = self
            .entries
            .lock()
            .expect("LeaseFixtureNotifications lock poisoned");
        entries.push(notification);
    }

    /// Return a snapshot of all notifications received so far.
    pub fn snapshot(&self) -> Vec<LeaseFixtureNotification> {
        let entries = self
            .entries
            .lock()
            .expect("LeaseFixtureNotifications lock poisoned");
        entries.clone()
    }
}

/// Callback to return an initial lease state for a number of times then switch.
struct SimpleTransitionCallback {
    change_at: usize,
    state_one: State,
    state_two: State,
}

#[async_trait::async_trait]
impl ICallback<usize> for SimpleTransitionCallback {
    async fn invoke(&self, state: &mut usize, candidate: bool) -> Result<State> {
        // Track current count and increase it immediately.
        let count = *state;
        *state += 1;

        // Always idle when not a candidate.
        if !candidate {
            return Ok(State::Idle);
        }

        // Pick the correct state based on number of watch calls.
        if count < self.change_at {
            Ok(self.state_one)
        } else {
            Ok(self.state_two)
        }
    }
}

impl LeaseFixture<usize> {
    /// Lease fixture that returns the given state whenever watched.
    pub fn simple_transition(
        state_one: State,
        state_two: State,
        change_at: usize,
    ) -> LeaseFixture<usize> {
        let callback = SimpleTransitionCallback {
            change_at,
            state_one,
            state_two,
        };
        LeaseFixture::new(0, callback)
    }
}
