apiVersion: replicante.io/v0
kind: NodeAction

metadata:
  namespace: default
  cluster: mongo-rs
  node: https://localhost:10001
  #approval: granted
  approval: required

spec:
  action: agent.replicante.io/test.ping
  args:
    count: 5
