apiVersion: replicante.io/v0
kind: NodeAction

metadata:
  namespace: default
  cluster: mongo-rs
  node: https://localhost:10001
  #approval: granted
  approval: required

spec:
  action: agent.replicante.io/debug.progress
  args:
    test: true
    parameter: 12
