[package]
name = "replicante_externals_mongodb"
version = "0.2.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante reusable logic for MongoDB"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicore"
license = "MIT"


[dependencies]
failure = "^0.1.5"
lazy_static = "^1.0.0"
opentracingrust = "^0.4.0"
prometheus = "^0.13"
semver = { version = "^1.0", features = ["serde"]}
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.2.0"

replicante_models_api = { path = "../../common/models/api" }
replicante_models_core = { path = "../../models/core" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_util_tracing = { path = "../../common/util/tracing" }

[dependencies.mongodb]
default-features = false
features = ["sync"]
version = "^2.0"
