[package]
name = "replicore-cluster-view"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "Estimated view of a full cluster built on collected data"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
futures-util = "^0.3"
serde = { version = "^1.0", features = ["derive"] }
thiserror = "^1.0"
uuid = { version = "^1.4", features = ["serde", "v4"] }

replisdk = { version = "^0.1", features = ["replicore-models"] }

replicore-context = { path = "../../context" }
replicore-store = { path = "../../store" }

[dev-dependencies]
serde_json = "^1.0"
