[package]
name = "replicore_cluster_view"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Syntetic Cluster View logic"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
keywords = ["automation", "datastore", "operations"]
license = "MIT"


[dependencies]
anyhow = "^1.0"
chrono = "^0.4.0"
serde = { version = "^1.0", features = ["derive"] }
thiserror = "^1.0"
uuid = { version = "^1.0", features = ["serde"] }

replicante_models_agent = { path = "../../../common/models/agent" }
replicante_models_core = { path = "../../../models/core" }

[dev-dependencies]
serde_json = "^1.0.0"
