[package]
name = "replicore-events-sqlite"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "RepliCore events backed by an SQLite DB"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
once_cell = "^1.18"
opentelemetry_api = "^0.20"
prometheus = "^0.13"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.0"
refinery = { version = "^0.8", features = ["rusqlite"] }
rusqlite = { version = "^0.29", features = ["bundled"] }
thiserror = "^1.0"

# Changes needed to support custom errors have not been published yet so point directly to repo.
#tokio-rusqlite = { version = "^0.4", optional = true }
tokio-rusqlite = { git = "https://github.com/programatik29/tokio-rusqlite.git", rev = "ee94a85" }

replicore-context = { path = "../../context" }
replicore-events = { path = "../" }

replisdk = { version = "^0.1", features = ["utils-encoding", "utils-metrics", "utils-trace"] }
