[package]
name = "replicore_util_errors"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Utilites to better support errors"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicore"
license = "MIT"


[dependencies]
anyhow = "^1.0.53"
failure = "^0.1.5"
serde = "^1.0"
