[package]
name = "replicore-task-orchestrate"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "RepliCore task to monitor and orchestrate clusters"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
once_cell = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.0"
thiserror = "^1.0"
time = { version = "^0.3", features = ["formatting", "parsing", "serde"] }
uuid = { version = "^1.4", features = ["serde", "v4"] }

replisdk = { version = "^0.1", features = [
  "platform-models",
  "replicore-models",
] }

repliagent-client = { path = "../../../client/agent" }

replicore-cluster-models = { path = "../../../core/cluster/models" }
replicore-cluster-view = { path = "../../../core/cluster/view" }
replicore-context = { path = "../../../core/context"}
replicore-errors = { path = "../../../core/errors"}
replicore-events = { path = "../../../core/events"}
replicore-injector = { path = "../../../core/injector" }
replicore-oaction = { path = "../../../core/oaction" }
replicore-sdk = { path = "../../../core/sdk" }
replicore-store = { path = "../../../core/store" }
replicore-tasks = { path = "../../../core/tasks" }

replicore-oaction-platform = { path = "../../oaction/platform" }
