//! Unit test fixture to stub out leases and inspect their use.
use std::sync::Arc;
use std::sync::Mutex;
use std::time::Duration;

use anyhow::Result;
use serde_json::Value as Json;

use replicore_context::Context;

use crate::ICoordinated;
use crate::ILease;
use crate::ILeaseRegistry;
use crate::Lease;
use crate::LeaseFactory;
use crate::LeaseFactorySyncArgs;
use crate::LeaseRegistry;
use crate::LeaseRegistryArgs;
use crate::State;

/// Unit test fixture to test the implementation of the [`Coordinator`](crate::Coordinator).
pub struct CoordinatedFixture {
    /// Time to wait before returning from the primary/secondary handlers.
    delay: Duration,

    /// Collection of notifications sent by the fixtures.
    notifications: CoordinatedFixtureNotifications,
}

impl CoordinatedFixture {
    /// Get a handle to access notifications generated by the fixture.
    pub fn notifications(&self) -> CoordinatedFixtureNotifications {
        self.notifications.clone()
    }

    /// Set the delay after which [`ICoordinated::primary`] and [`ICoordinated::secondary`] stop.
    ///
    /// While real tasks are expected to loop forever, unit tests need to stop.
    pub fn set_delay(mut self, delay: Duration) -> Self {
        self.delay = delay;
        self
    }
}

impl Default for CoordinatedFixture {
    fn default() -> Self {
        CoordinatedFixture {
            delay: Duration::from_millis(10),
            notifications: Default::default(),
        }
    }
}

#[async_trait::async_trait]
impl ICoordinated for CoordinatedFixture {
    async fn primary(&self, _: &Context) -> Result<()> {
        self.notifications
            .append(CoordinatedFixtureNotification::Primary);
        tokio::time::sleep(self.delay).await;
        Ok(())
    }

    async fn secondary(&self, _: &Context) -> Result<()> {
        self.notifications
            .append(CoordinatedFixtureNotification::Secondary);
        tokio::time::sleep(self.delay).await;
        Ok(())
    }

    async fn transition(&self, _: &Context, from: State, to: State) -> Result<()> {
        let notification = CoordinatedFixtureNotification::Transition(from, to);
        self.notifications.append(notification);
        Ok(())
    }
}

/// Possible notifications sent by the fixture to allow state inspection and history in tests.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CoordinatedFixtureNotification {
    /// The coordinated fixture's primary handler was invoked.
    Primary,

    /// The coordinated fixture's secondary handler was invoked.
    Secondary,

    /// The coordinated fixture was notified of a state transition.
    ///
    /// The notification carries the `(from, to)` states of the transition.
    Transition(State, State),
}

/// Shared access to coordinated fixture notifications.
pub type CoordinatedFixtureNotifications = FixtureNotifications<CoordinatedFixtureNotification>;

/// Callback to determine the [`State`] of a lease returned by `watch`.
#[async_trait::async_trait]
pub trait ICallback<S: Send>: Send {
    /// Determine the [`State`] of a lease returned by `watch`.
    async fn invoke(&self, state: &mut S, candidate: bool) -> Result<State>;
}

/// Callback to return a fixed lease state all the time.
pub struct FixedLeaseCallback {
    state: State,
}

impl FixedLeaseCallback {
    /// New callback that always returns the given state.
    pub fn new(state: State) -> FixedLeaseCallback {
        FixedLeaseCallback { state }
    }
}

#[async_trait::async_trait]
impl ICallback<()> for FixedLeaseCallback {
    async fn invoke(&self, _: &mut (), candidate: bool) -> Result<State> {
        if candidate {
            return Ok(self.state);
        }
        Ok(State::Idle)
    }
}

impl LeaseFixture<()> {
    /// Lease fixture that returns the given state whenever watched.
    pub fn fixed(state: State) -> LeaseFixture<()> {
        let callback = FixedLeaseCallback::new(state);
        LeaseFixture::new((), callback)
    }
}

/// Shared access to the fixture notifications set.
#[derive(Clone)]
pub struct FixtureNotifications<T: Clone> {
    /// List of received notifications being tracked.
    entries: Arc<Mutex<Vec<T>>>,
}

impl<T: Clone> Default for FixtureNotifications<T> {
    fn default() -> Self {
        FixtureNotifications {
            entries: Arc::new(Mutex::new(Vec::new())),
        }
    }
}

impl<T: Clone> FixtureNotifications<T> {
    /// Append a notification to the notifications set.
    fn append(&self, notification: T) {
        let mut entries = self
            .entries
            .lock()
            .expect("FixtureNotifications lock poisoned");
        entries.push(notification);
    }

    /// Return a snapshot of all notifications received so far.
    pub fn snapshot(&self) -> Vec<T> {
        let entries = self
            .entries
            .lock()
            .expect("FixtureNotifications lock poisoned");
        entries.clone()
    }
}

/// Fixture to stub out leases in unit tests.
pub struct LeaseFixture<S: Send> {
    callback: Box<dyn ICallback<S>>,
    first_watch: bool,
    notifications: LeaseFixtureNotifications,
    state: S,
    watch_delay: Duration,
}

#[async_trait::async_trait]
impl<S: Send> ILease for LeaseFixture<S> {
    async fn step_down(&mut self, _: &Context) -> Result<()> {
        self.notifications
            .append(LeaseFixtureNotification::SteppedDown);
        Ok(())
    }

    async fn watch(&mut self, _: &Context, candidate: bool) -> Result<State> {
        if !self.first_watch {
            tokio::time::sleep(self.watch_delay).await;
        }
        self.first_watch = false;

        let state = self.callback.invoke(&mut self.state, candidate).await;
        let notification = match &state {
            Ok(state) => LeaseFixtureNotification::Watched(state.clone()),
            Err(error) => LeaseFixtureNotification::WatchError(error.to_string()),
        };
        self.notifications.append(notification);
        return state;
    }
}

impl<S: Send> LeaseFixture<S> {
    /// Initialise a new lease backend for unit tests.
    fn boxed(state: S, callback: Box<dyn ICallback<S>>) -> LeaseFixture<S> {
        LeaseFixture {
            callback,
            first_watch: true,
            notifications: Default::default(),
            state,
            watch_delay: Duration::from_millis(20),
        }
    }

    /// Initialise a new lease backend for unit tests.
    pub fn new<C>(state: S, callback: C) -> LeaseFixture<S>
    where
        C: ICallback<S> + 'static,
    {
        let callback = Box::new(callback);
        LeaseFixture::boxed(state, callback)
    }

    /// Get a handle to access notifications generated by the fixture.
    pub fn notifications(&self) -> LeaseFixtureNotifications {
        self.notifications.clone()
    }

    /// Set the delay time every watch call after the first will wait before returning.
    ///
    /// The watch delay is needed because lease backends are managed by a background task
    /// and therefore polled even if the test is not actively interacting with them yet.
    /// This prevents one of the tokio threads from using as much CPU as it can to forever
    /// invoke the callback and make things messier.
    ///
    /// The delay is constant across all invocations of the watch callback.
    /// If a test requires changing of the delay depending on conditions it should set this delay
    /// to zero and implement its own delay in the [`ICallback`].
    pub fn set_watch_delay(mut self, delay: Duration) -> Self {
        self.watch_delay = delay;
        self
    }
}

impl<S: Clone + Send + Sync> LeaseFixture<S> {
    pub fn factory<C>(state: S, callback: C) -> LeaseFixtureFactory<S>
    where
        C: Fn() -> Box<dyn ICallback<S>> + Send + Sync + 'static,
    {
        LeaseFixtureFactory::new(state, callback)
    }
}

/// Factory for [`LeaseFixture`] backed leases.
pub struct LeaseFixtureFactory<S: Clone + Send + Sync> {
    /// Function to create callbacks for the generated fixtures.
    callback: Arc<dyn Fn() -> Box<dyn ICallback<S>> + Send + Sync>,

    /// Initial state for generated fixtures.
    init_state: S,
}

impl<S: Clone + Send + Sync> LeaseFixtureFactory<S> {
    /// Initialise a new lease backend for unit tests.
    pub fn new<C>(state: S, callback: C) -> LeaseFixtureFactory<S>
    where
        C: Fn() -> Box<dyn ICallback<S>> + Send + Sync + 'static,
    {
        let callback = Arc::new(callback);
        LeaseFixtureFactory {
            callback,
            init_state: state,
        }
    }
}

#[async_trait::async_trait]
impl<S: Clone + Send + Sync + 'static> LeaseFactory for LeaseFixtureFactory<S> {
    fn conf_check(&self, _: &Context, _: &Json) -> Result<()> {
        Ok(())
    }

    async fn registry(&self, _: &Context, _: &Json) -> Result<LeaseRegistry> {
        let reg = LeaseFixtureFactory {
            callback: self.callback.clone(),
            init_state: self.init_state.clone(),
        };
        Ok(LeaseRegistry::from(reg))
    }

    fn register_metrics(&self, _: &prometheus::Registry) -> Result<()> {
        Ok(())
    }

    async fn sync<'a>(&self, _: LeaseFactorySyncArgs<'a>) -> Result<()> {
        Ok(())
    }
}

#[async_trait::async_trait]
impl<S: Clone + Send + Sync + 'static> ILeaseRegistry for LeaseFixtureFactory<S> {
    /// Create a [`Lease`] object with the correct backend.
    async fn lease<'a>(&self, args: LeaseRegistryArgs<'a>) -> Result<Lease> {
        let callback = (self.callback)();
        let state = self.init_state.clone();
        let lease = LeaseFixture::boxed(state, callback);
        let lease = Lease::new(args.context.clone(), args.lease_id, lease);
        Ok(lease)
    }
}

/// Possible notifications sent by the fixture to allow state inspection and history in tests.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum LeaseFixtureNotification {
    /// A step down request was handled.
    SteppedDown,

    /// The fixture callback was invoked, moving the lease to the given state.
    Watched(State),

    /// The fixture callback was invoked, resulting in an error.
    WatchError(String),
}

/// Shared access to lease fixture notifications.
pub type LeaseFixtureNotifications = FixtureNotifications<LeaseFixtureNotification>;

/// Callback to return an initial lease state for a number of times then switch.
struct SimpleTransitionCallback {
    change_at: usize,
    state_one: State,
    state_two: State,
}

#[async_trait::async_trait]
impl ICallback<usize> for SimpleTransitionCallback {
    async fn invoke(&self, state: &mut usize, candidate: bool) -> Result<State> {
        // Track current count and increase it immediately.
        let count = *state;
        *state += 1;

        // Always idle when not a candidate.
        if !candidate {
            return Ok(State::Idle);
        }

        // Pick the correct state based on number of watch calls.
        if count < self.change_at {
            Ok(self.state_one)
        } else {
            Ok(self.state_two)
        }
    }
}

impl LeaseFixture<usize> {
    /// Lease fixture that returns the given state whenever watched.
    pub fn simple_transition(
        state_one: State,
        state_two: State,
        change_at: usize,
    ) -> LeaseFixture<usize> {
        let callback = SimpleTransitionCallback {
            change_at,
            state_one,
            state_two,
        };
        LeaseFixture::new(0, callback)
    }
}
