use chrono::DateTime;
use chrono::Utc;

use super::Event;
use super::EventData;


mod agent;
mod cluster;

use self::agent::AgentBuilder;
use self::cluster::ClusterBuilder;


/// Build `Event`s, validating inputs.
pub struct EventBuilder {
    timestamp: Option<DateTime<Utc>>,
}

impl EventBuilder {
    pub fn new() -> EventBuilder {
        EventBuilder {
            timestamp: None,
        }
    }

    /// Specialise the builder into an agent events builder.
    pub fn agent(self) -> AgentBuilder {
        AgentBuilder::new_builder(self)
    }

    /// Specialise the builder into a cluster events builder.
    pub fn cluster(self) -> ClusterBuilder {
        ClusterBuilder::new_builder(self)
    }

    /// Set the event occurrence timestamp.
    pub fn timestamp(mut self, timestamp: DateTime<Utc>) -> Self {
        self.timestamp = Some(timestamp);
        self
    }
}

impl EventBuilder {
    /// Helper method to finish building an event.
    ///
    /// The specialised buidlers create the `EventData` argument.
    /// Add `Event` metadata is then added and/or generated by this method.
    fn build(self, data: EventData) -> Event {
        Event {
            payload: data,
            timestamp: self.timestamp.unwrap_or_else(Utc::now),
        }
    }
}
