[package]
name = "replicore-coordinator"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "RepliCore distributed coordination interface"
homepage = "https://www.replicante.io/"
license = "MIT"

[features]
# Enable utilities for unit testing.
test-fixture = []

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
futures = "^0.3"
prometheus = "^0.13"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.7"
tokio = { version = "^1.4", features = ["macros", "rt", "sync", "time"] }

replicore-context = { path = "../context" }

replisdk = { version = "^0.1", features = ["runtime-shutdown"] }

[dev-dependencies]
replicore-context = { path = "../context", features = ["test-fixture"] }

replisdk = { version = "^0.1", features = ["runtime-shutdown", "test-fixture"] }
