[package]
name = "replicante_store_primary"
version = "0.5.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Replicante primary data store interface"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicore"
license = "MIT"


[features]
with_test_support = []


[dependencies]
anyhow = "^1.0"
failure = "^0.1.5"
lazy_static = "^1.0"
opentracingrust = "^0.4.0"
regex = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.2"

replicore_cluster_view = { path = "../../core/cluster/view" }
replicante_externals_mongodb = { path = "../../externals/mongodb" }
replicante_models_api = { path = "../../common/models/api" }
replicante_models_core = { path = "../../models/core" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_util_tracing = { path = "../../common/util/tracing" }

[dependencies.chrono]
features = ["serde"]
version = "^0.4.0"

[dependencies.mongodb]
default-features = false
features = ["bson-chrono-0_4", "sync"]
version = "^2.0"

[dependencies.replisdk]
features = [
  "replicore-models",
  "platform-models",
]
version = "^0.1"

[dependencies.uuid]
features = ["serde", "v4"]
version = "^1.0"
