[package]
name = "replicante_store_primary"
version = "0.5.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante primary data store interface"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[features]
with_test_support = []


[dependencies]
bson = "^1.1.0" # bound by mongodb crate
failure = "^0.1.5"
lazy_static = "^1.0.0"
opentracingrust = "^0.4.0"
regex = "^1.0.0"
serde = "^1.0.34"
serde_derive = "^1.0.34"
serde_json = "^1.0.39"
slog = "^2.2.0"

replicante_externals_mongodb = { path = "../../externals/mongodb" }
replicante_models_api = { path = "../../common/models/api" }
replicante_models_core = { path = "../../models/core" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_util_tracing = { path = "../../common/util/tracing" }

[dependencies.chrono]
features = ["serde"]
version = "^0.4.0"

[dependencies.mongodb]
default-features = false
features = ["sync"]
version = "^1.1.0"

[dependencies.uuid]
features = ["serde", "v4"]
version = "^0.8.0"
