[package]
name = "replicore_cluster_orchestrate"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Replicante Core logic to orchestate a cluster"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"

[dependencies]
anyhow = "^1.0"
chrono = { version = "^0.4.0", features = ["serde"] }
failure = "^0.1.5"
lazy_static = "^1.0"
opentracingrust = "^0.4.0"
prometheus = "^0.13"
serde_json = "^1.0"
slog = "^2.1"
thiserror = "^1.0"
uuid = { version = "^1.0", features = ["serde", "v4"] }

replicante_agent_client = { path = "../../../agent/client" }
replicante_models_agent = { path = "../../../common/models/agent" }
replicante_models_core = { path = "../../../models/core" }
replicante_service_coordinator = { path = "../../../service/coordinator" }
replicante_store_primary = { path = "../../../store/primary" }
replicante_stream_events = { path = "../../../stream/events" }
replicante_util_failure = { path = "../../../common/util/failure" }
replicore_cluster_view = { path = "../view" }
replicore_iface_orchestrator_action = { path = "../../interface/orchestrator_action" }
replicore_util_errors = { path = "../../util/errors" }

[dev-dependencies]
replicore_action_debug = { path = "../../orchestrator_action/debug" }

[dev-dependencies.replicante_agent_client]
features = ["with_test_support"]
path = "../../../agent/client"

[dev-dependencies.replicante_store_primary]
features = ["with_test_support"]
path = "../../../store/primary"

[dev-dependencies.replicante_stream_events]
features = ["with_test_support"]
path = "../../../stream/events"

[dev-dependencies.replicore_iface_orchestrator_action]
features = ["test-api"]
path = "../../interface/orchestrator_action"
