apiVersion: 1
deleteDatasources: []
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://host.containers.internal:9090/
    isDefault: true
    version: 1
    editable: false
