apiVersion: replicante.io/v0
kind: ClusterSpec
spec:
  ns_id: default
  cluster_id: declared-mongo-rs
  active: true

  platform:
    # Default to current.
    #namespace: default
    name: playground
  
  declaration:
    definition:
      cluster_id: declared-mongo-rs
      store: mongo/rs
      store_version: '4.2.0'
      nodes:
        default:
          desired_count: 3
          node_class: play.mode
