[package]
name = "replicore_task_discovery"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Task to discover clusters"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[dependencies]
failure = "^0.1.5"
lazy_static = "^1.0"
opentracingrust = "^0.4.0"
prometheus = "^0.13.0"
slog = "^2.2.0"

replicante_cluster_discovery = { path = "../../../cluster/discovery" }
replicante_models_core = { path = "../../../models/core" }
replicante_service_tasks = { path = "../../../service/tasks" }
replicante_store_primary = { path = "../../../store/primary" }
replicante_stream_events = { path = "../../../stream/events" }
replicante_util_failure = { path = "../../../common/util/failure" }
replicante_util_tracing = { path = "../../../common/util/tracing" }

replicore_models_tasks = { path = "../../../models/tasks" }

[dependencies.replisdk]
features = [
  "replicore-models",
  "platform-models",
]
version = "^0.1"
