[package]
name = "replicore-auth-insecure"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

description = "RepliCore Auth implementations for unprotected access"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
prometheus = "^0.13"
serde_json = "^1.0"

replicore-auth = { path = "../" }
replicore-context = { path = "../../context" }
