[package]
name = "replicore_action_platform"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"

description = "Replicante Core's Platform orchestrator actions"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[dependencies]
anyhow = "^1.0"
failure = "^0.1.5"
reqwest = { version = "^0.11", features = ["blocking", "gzip", "json"]}
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^1.0"

replicante_models_core = { path = "../../../models/core" }
replicante_store_primary = { path = "../../../store/primary" }
replicore_iface_orchestrator_action = { path = "../../interface/orchestrator_action" }

[dependencies.replisdk]
features = [
  "replicore-models",
  "platform-models",
]
version = "^0.1"
