[package]
name = "replicante_service_healthcheck"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante Core component and dependency HealthCheck service"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicore"
keywords = ["replicante"]
license = "MIT"


[dependencies]
replicante_models_api = { path = "../../common/models/api" }
