[package]
name = "replicore-clients-agent"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "Registry of Agent API clients factories"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
thiserror = "^1.0"

replisdk = { version = "^0.1", features = ["replicore-models"] }

repliagent-client = { path = "../../../client/agent" }
repliagent-client-http = { path = "../../../client/agent/http" }
replicore-context = { path = "../../../core/context" }
