[package]
name = "replictl"
version = "0.8.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2021"
build = "../../build.rs"

description = "Replicante Core command line tool"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
readme = "../../README.md"
license = "MIT"


[[bin]]
name = "replictl"
path = "src/main.rs"


[lib]
name = "replictl"
path = "src/lib.rs"


[dependencies]
anyhow = "^1.0"
clap = { version = "^4.0", features = ["derive", "env"] }
dialoguer = "^0.10"
prettytable-rs = "^0.9"
serde_json = "^1.0"
serde_yaml = "^0.9"
slog = "^2.1"
slog-json = "^2.3"
thiserror = "^1.0"

replicante_models_core = { path = "../../models/core" }
replicante_util_failure = { path = "../../common/util/failure" }

[dependencies.reqwest]
# Use rustls-tls to access PEM files as Identity objects.
features = ["json", "rustls-tls"]
version = "^0.11"

[dependencies.serde]
features = ["derive"]
version = "^1.0"

[dependencies.tokio]
features = ["full"]
version = "^1.24"

[dependencies.uuid]
features = ["serde", "v4"]
version = "^1.0"


[build-dependencies]
git2 = "^0.15.0"
