[package]
name = "replictl"
version = "0.8.0"
build = "../../build.rs"

edition = "2021"
rust-version = "1.75"

description = "Command line tool to interact with Replicante Core servers"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicore"
readme = "../../README.md"
license = "MIT"

[[bin]]
name = "replictl"
path = "src/main.rs"

[lib]
name = "replictl"
path = "src/lib.rs"

[dependencies]
anyhow = "^1.0"
clap = { version = "^4.3", features = ["derive", "env"] }
comfy-table = "^7.1"
futures = "^0.3"
glob = "^0.3"
inquire = "^0.7"
once_cell = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
serde_yaml = "^0.9"
slog = "^2.1"
time = { version = "^0.3", features = ["formatting", "macros"] }
thiserror = "^1.0"
tokio = { version = "^1.0", features = [
  "fs",
  "io-util",
  "io-std",
  "macros",
  "rt",
  "rt-multi-thread",
] }
uuid = { version = "^1.4", features = ["serde", "v4"] }

replicore-client = { path = "../../client/core" }

replisdk = { version = "^0.1", features = ["replicore-models"] }

#slog-json = "^2.3"

#replicante_models_core = { path = "../../models/core" }
#replicante_util_failure = { path = "../../common/util/failure" }

#[dependencies.uuid]
#features = ["serde", "v4"]
#version = "^1.0"

[build-dependencies]
git2 = "^0.18.0"
