[package]
name = "replicore_models_tasks"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante Core tasks related models"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[features]
with_test_support = ["replicante_service_tasks/with_test_support"]


[dependencies]
failure = "^0.1.5"
serde = "^1.0.34"
serde_derive = "^1.0.34"
serde_json = "^1.0.0"

replicante_models_core = { path = "../core" }
replicante_service_tasks = { path = "../../service/tasks" }

[dependencies.chrono]
features = ["serde"]
version = "^0.4.0"

[dependencies.replisdk]
features = ["replicore-models"]
version = "^0.1"
