[package]
name = "replicore-cluster-models"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "Control Plane models for cluster related operations"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
time = { version = "^0.3", features = ["formatting", "parsing", "serde"] }
uuid = "^1.4"

replisdk = { version = "^0.1", features = ["utils-error_json"] }
