[package]
name = "replicore-cluster-models"
version = "0.1.0"

edition = "2021"
rust-version = "1.70"

description = "Control Plane models for cluster related operations"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
time = { version = "^0.3", features = ["formatting", "parsing", "serde"] }
