[package]
name = "replicante_stream"
version = "0.1.1"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante common streaming logic"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
keywords = ["replicante"]
license = "MIT"


[features]
with_test_support = ["crossbeam-channel"]


[dependencies]
failure = "^0.1.5"
futures = "^0.3.0"
humthreads = "^0.2.0"
lazy_static = "^1.0"
opentracingrust = "^0.4.0"
prometheus = "^0.13.0"
rand = "^0.8.0"
rdkafka = "^0.28.0"
sentry = "^0.27.0"
serde = "^1.0.34"
serde_derive = "^1.0.34"
serde_json = "^1.0.39"
slog = "^2.1.1"

replicante_externals_kafka = { path = "../../externals/kafka" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_util_failure = { path = "../../common/util/failure" }

[dependencies.crossbeam-channel]
optional = true
version = "^0.5.0"


[dev-dependencies]
humthreads = { version = "^0.2.0", features = ["with_test_support"] }
