[package]
name = "replicore"
version = "0.8.0"
build = "../../build.rs"

edition = "2021"
rust-version = "1.70"

description = "Replicante Core is a Control Plane for distributed store orchestration"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicore"
readme = "../../README.md"
keywords = ["automation", "datastore", "operations"]
license = "MIT"

[[bin]]
name = "replicore"
path = "src/main.rs"

[lib]
name = "replicore"
path = "src/lib.rs"

[features]
default = [
  "sqlite-impls",
]

# Include SQLite implementations for the Control Plane dependencies.
sqlite-impls = [
  "replicore-events-sqlite",
  "replicore-store-sqlite",
  "replicore-tasks-sqlite",
]

[dependencies]
actix-web = "^4.0"
anyhow = "^1.0"
async-trait = "^0.1"
clap = { version = "^4.3", features = ["derive"] }
futures-util = "^0.3"
jsonschema = "^0.17"
once_cell = "^1.0"
prometheus = "^0.13"
serde = "^1.0"
serde_json = "^1.0"
slog = "^2.7"
thiserror = "^1.0"
tokio = "^1.0"

replisdk = { version = "^0.1", features = [
  "runtime-actix_builder",
  "runtime-shutdown",
  "runtime-shutdown_actix",
  "runtime-telemetry",
] }

replicore-auth = { path = "../../core/auth" }
replicore-conf = { path = "../../core/conf" }
replicore-context = { path = "../../core/context" }
replicore-events = { path = "../../core/events" }
replicore-injector = { path = "../../core/injector" }
replicore-store = { path = "../../core/store" }
replicore-tasks = { path = "../../core/tasks" }

# Control Plane logic implementations.
replicore-task-discovery = { path = "../../core-logic/task/discovery" }

# Supported interface backend implementations for compile time customisation.
replicore-auth-insecure = { path = "../../core/auth/insecure" }
replicore-events-sqlite = { path = "../../core/events/sqlite", optional = true }
replicore-store-sqlite = { path = "../../core/store/sqlite", optional = true }
replicore-tasks-sqlite = { path = "../../core-impl/tasks/sqlite", optional = true }

[dev-dependencies]
replicore-auth-insecure = { path = "../../core/auth/insecure" }
replicore-context = { path = "../../core/context", features = ["test-fixture"] }
replicore-injector = { path = "../../core/injector", features = ["test-fixture"] }

[build-dependencies]
git2 = "^0.18.0"
