[package]
name = "replicore-store-sqlite"
version = "0.1.0"

edition = "2021"
rust-version = "1.75"

description = "RepliCore persistent store backed by an SQLite DB"
homepage = "https://www.replicante.io/"
license = "MIT"

[dependencies]
anyhow = "^1.0"
async-trait = "^0.1"
futures = "^0.3"
once_cell = "^1.18"
opentelemetry_api = "^0.20"
prometheus = "^0.13"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
slog = "^2.0"
refinery = { version = "^0.8", features = ["rusqlite"] }
rusqlite = { version = "^0.29", features = ["bundled"] }
thiserror = "^1.0"
tokio-rusqlite = "^0.4"

replicore-cluster-models = { path = "../../cluster/models" }
replicore-context = { path = "../../context" }
replicore-store = { path = "../" }

replisdk = { version = "^0.1", features = [
  "replicore-models",
  "utils-encoding",
  "utils-metrics",
  "utils-trace",
] }

[dev-dependencies]
tokio = { version = "^1.0", features = ["macros", "rt"] }

replicore-context = { path = "../../context", features = ["test-fixture"] }
