name: Rust Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Stable rust is the version we aim to use for builds.
  check-stable:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Replicante Core
      - name: Replicante Core
        run: ci/check-workspace.sh --full Core Cargo.toml

      # Replicante development tool CI.
      - name: Replicante Development Tool
        run: ci/check-workspace.sh --full "Replicante Development Tool" devtools/replidev/Cargo.toml

  # Earliest version of rust supported (breaking clippy check).
  check-min-rust:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
          components: rustfmt, clippy

      # Replicante Core
      - name: Replicante Core
        run: ci/check-workspace.sh Core Cargo.toml

      # Replicante development tool CI.
      - name: Replicante Development Tool
        run: ci/check-workspace.sh "Replicante Development Tool" devtools/replidev/Cargo.toml
