name: Rust Tests and Lints

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

# TODO: I'd like to re-add the cargo audit task but I'm not sure yet where it should be.
jobs:
  tests-and-lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable   # Version of rust we aim to use.
          - 1.56.0   # Earliest version of rust supported.
    continue-on-error: ${{ matrix.rust != 'stable' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      # Replicante Core
      - name: Replicante Core
        run: ci/test-and-lint-workspace.sh Core Cargo.toml

      # Replicante development tool CI.
      - name: Replicante Development Tool
        run: ci/test-and-lint-workspace.sh "Replicante Development Tool" devtools/replidev/Cargo.toml

  nightly-tests-and-lints:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      # Replicante Core
      - name: Replicante Core
        run: ci/test-and-lint-workspace.sh Core Cargo.toml || true

      # Replicante development tool CI.
      - name: Replicante Development Tool
        run: ci/test-and-lint-workspace.sh "Replicante Development Tool" devtools/replidev/Cargo.toml || true
